---
title: "Solución parcial"
author: "Jennifer Salazar"
date: "17/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(haven)
kidiq <- read_dta("Datos/ARM_Data/child.iq/kidiq.dta")
```


```{r}
kidiq1 <- kidiq[kidiq$mom_work==1,]
```



```{r}
modelo1 <- lm(kid_score~mom_hs+mom_iq, data=kidiq1)
summary(modelo1)
```



```{r}
datos_nuevos <- data.frame(mom_hs=1, mom_iq=133)

predict(modelo1, datos_nuevos, interval="prediction", level=0.95)
```

```{r}
library(MASS)
epil <- MASS::epil

levels(epil$trt)
```

```{r}
1.0779+ 3.4458*(3.15) + 2.7350*(0) + 3.5911*(3) -2.4887*(2)
```



# Ejercicioo 



```{r}
library(haven)
risky <- read_dta("risky_behaviors.dta")

risky$fupacts <- round(risky$fupacts, digits=0)
```


```{r}
modelo <- glm(fupacts ~ sex+couples+women_alone, data=risky,
              family = poisson(link="log"))

summary(modelo)
coef(mod)
```



# Simulación


```{r}
gen_dat <- function(n){
  x1 <- rbinom(n=n, size = 4, prob = 0.89)
  x2 <- rpois(n=n, lambda = 3)
  media <- -6 + 4*x1 + 5*x2
  y <- rnorm(n=n, mean = media, sd=2)
  data.frame(y=y, x1=x1, x2=x2)
}


set.seed(402212)
datos <- gen_dat(n=9)
mod <- lm(y ~ x1 + x2, data=datos)
coef(mod)

```

